name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:

  cypress-run:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run